language: c
matrix:
  include:
  - name: linux-xenial-gcc
    os: linux
    env: HINTS=linux
    compiler: gcc
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-bionic-gcc
    os: linux
    env: HINTS=linux
    dist: bionic
    compiler: gcc
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-xenial-clang
    os: linux
    env: HINTS=linux
    compiler: clang
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-xenial-gcc-x11
    os: linux
    env: HINTS=linux-x11
    compiler: gcc
    addons:
      apt:
        packages:
        - libx11-dev
        - libxaw7-dev
        - xfonts-utils
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-xenial-gcc-qt5
    os: linux
    env: HINTS=linux-qt5
    compiler: gcc
    addons:
      apt:
        packages:
        - libx11-dev
        - libxaw7-dev
        - xfonts-utils
        - qtbase5-dev
        - qtmultimedia5-dev
        - qtbase5-dev-tools
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make QT_SELECT=5 MOC=moc install
  - name: linux-bionic-gcc-x11
    os: linux
    env: HINTS=linux-x11
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
        - libx11-dev
        - libxaw7-dev
        - xfonts-utils
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-xenial-gcc-minimal
    os: linux
    env: HINTS=linux-minimal
    compiler: gcc
    script: |
      cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
      sed -i '/^#define CLIPPING/d'       include/config.h
      sed -i '/^#define COMPRESS/d'       include/config.h
      #sed -i '/^#define DOAGAIN/d'        include/config.h
      sed -i '/^#define DUMPLOG/d'        include/config.h
      #sed -i '/^#define GDBPATH/d'        include/config.h
      #sed -i '/^#define GREPPATH/d'       include/config.h
      sed -i '/^#define INSURANCE/d'      include/config.h
      sed -i '/^#define LOGFILE/d'        include/config.h
      sed -i '/^#define NEWS/d'           include/config.h
      sed -i '/^#define PANICLOG/d'       include/config.h
      #sed -i '/^#define STATUS_HILITES/d' include/config.h
      sed -i '/^#define SYSCF/d'          include/config.h
      sed -i '/^#define USER_SOUNDS/d'    include/config.h
      sed -i '/^#define XLOGFILE/d'       include/config.h
      sed -i '/^#define MAIL/d'           include/unixconf.h
      sed -i '/^#define SHELL/d'          include/unixconf.h
      sed -i '/^#define SUSPEND/d'        include/unixconf.h
      sed -i 's/^#define TEXTCOLOR//'     include/unixconf.h
      make install
      cat dat/options
  - name: windows-visualstudio
    os: windows
    install: choco install winflexbison
    language: shell
    script:
    - "./win/win32/vs2017/travisci.sh"
#  - name: windows-mingw
#    os: windows
#    script:
#    - export ADD_CURSES=Y
#    - export PDCURSES_TOP=../lib/pdcurses
#    - sh sys/winnt/travis-gcc.sh
#    - test -d "lib/pdcurses" || exit 0
#    - cd src
#    - cp ../sys/winnt/Makefile.gcc ./Makefile
#    - mingw32-make install
  exclude:
  - os: osx
    osx_image: xcode10.2
    env: HINTS=macosx10.14
    compiler: clang
    script: cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../ && make install
notifications:
  email:
    recipients:
    - admin@hardfought.org
deploy:
  provider: releases
  api_key:
    secure: oySSfgCNflAimBvpw3nbgM2Dde5QuradhT6KCwaMFCH/vszqmJAOsr5OVUmZAbvBoy4ajAImixsAJR70ULr0VdWLo7cnOHfnPN6aOU48gl2iwgD9hmg+XTpkdWqATa2nVHbt0ZvHnhv8KaT25BLrF7b85DeVBJaZtbl+kSSYrQeUUBIDVU3Wa2xbhtlTNcIso2MeSRaFMNS3sAtOXtxWFgfSs3mQvPTxV5qtW7ydpIqjNkppTV3OWwZiC0MAmvQCErDhoswyxDUgTc05M4wxvy7fNZWDUt/o3prGZd2yCDDabcV0SJP2xBlLdfW4pY2U5CxJAtmkdx6JREZBM1RB2oaoNHwLhznrmNHqE46xCXp/9Lo+B+Oy40ZmFBJqYWVdXRT0bEBBN5GRs2s63NN/VhsBkF/SnF0AQIeLvH2ahKRuN+kAOqea6LVZJxrxCA3LmNMRT3BUCMqc2V3FQV7yC1/KtqxmWOYav6bnO294cxHf9cS6vXO633IMpJ8pmUzzJrLEDzZ8HDc8IxB7xpvDz5BKRJe2hkl/MpWuBP00jltaRZdt7Rt13AafAlcTmLSzzOCoJmMjKjC3bHozPUBbxnAnNML+4l57v1ie7GYW7nLtOs2clFGQSc14/mXsm53uOM/lFTxE2suyr160JzVYeiXx7r9bavy9tmPh55JrWqg=
  file_glob: true
  file:
    - "$TRAVIS_TAG.x86.zip"
  cleanup: false
  on:
    tags: true
  prerelease: true
  name: "Test release build of EvilHack 0.5.0"
  body: "This is an auto generated test release build of EvilHack 0.5.0"
