language: c
matrix:
  include:
  - name: linux-xenial-gcc
    os: linux
    env: HINTS=linux
    compiler: gcc
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-bionic-gcc
    os: linux
    env: HINTS=linux
    dist: bionic
    compiler: gcc
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-xenial-clang
    os: linux
    env: HINTS=linux
    compiler: clang
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-xenial-gcc-x11
    os: linux
    env: HINTS=linux-x11
    compiler: gcc
    addons:
      apt:
        packages:
        - libx11-dev
        - libxaw7-dev
        - xfonts-utils
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-xenial-gcc-qt5
    os: linux
    env: HINTS=linux-qt5
    compiler: gcc
    addons:
      apt:
        packages:
        - libx11-dev
        - libxaw7-dev
        - xfonts-utils
        - qtbase5-dev
        - qtmultimedia5-dev
        - qtbase5-dev-tools
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make QT_SELECT=5 MOC=moc install
  - name: linux-bionic-gcc-x11
    os: linux
    env: HINTS=linux-x11
    dist: bionic
    compiler: gcc
    addons:
      apt:
        packages:
        - libx11-dev
        - libxaw7-dev
        - xfonts-utils
    script:
    - cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
    - make install
  - name: linux-xenial-gcc-minimal
    os: linux
    env: HINTS=linux-minimal
    compiler: gcc
    script: |
      cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
      sed -i '/^#define CLIPPING/d'       include/config.h
      sed -i '/^#define COMPRESS/d'       include/config.h
      #sed -i '/^#define DOAGAIN/d'        include/config.h
      sed -i '/^#define DUMPLOG/d'        include/config.h
      #sed -i '/^#define GDBPATH/d'        include/config.h
      #sed -i '/^#define GREPPATH/d'       include/config.h
      sed -i '/^#define INSURANCE/d'      include/config.h
      sed -i '/^#define LOGFILE/d'        include/config.h
      sed -i '/^#define NEWS/d'           include/config.h
      sed -i '/^#define PANICLOG/d'       include/config.h
      #sed -i '/^#define STATUS_HILITES/d' include/config.h
      sed -i '/^#define SYSCF/d'          include/config.h
      sed -i '/^#define USER_SOUNDS/d'    include/config.h
      sed -i '/^#define XLOGFILE/d'       include/config.h
      sed -i '/^#define MAIL/d'           include/unixconf.h
      sed -i '/^#define SHELL/d'          include/unixconf.h
      sed -i '/^#define SUSPEND/d'        include/unixconf.h
      sed -i 's/^#define TEXTCOLOR//'     include/unixconf.h
      make install
      cat dat/options
  - name: windows-visualstudio
    os: windows
    install: choco install winflexbison
    language: shell
    script:
    - "./win/win32/vs2017/travisci.sh"
#  - name: windows-mingw
#    os: windows
#    script:
#    - export ADD_CURSES=Y
#    - export PDCURSES_TOP=../lib/pdcurses
#    - sh sys/winnt/travis-gcc.sh
#    - test -d "lib/pdcurses" || exit 0
#    - cd src
#    - cp ../sys/winnt/Makefile.gcc ./Makefile
#    - mingw32-make install
  exclude:
  - os: osx
    osx_image: xcode10.2
    env: HINTS=macosx10.14
    compiler: clang
    script: cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../ && make install
sudo: false
notifications:
  email:
    recipients:
    - admin@hardfought.org
deploy:
  provider: releases
  api_key:
    secure: Jw7YZTwL2BYZ52FAxrkDfXOdZnPRVnLMNDWIKqR6BrZEECp4HZmkWJFvCl1rMivz27d/O15x37U5UgWGPLz8TUYTOt+6Da24jRLL2hQKA+DUjqDqrnnKztrtkntvBWJaffvTWjL4w0B3dmjeZv7klAgmQEKQW/A4B943vnYgsZl5H/dxlRH1QnGpTK0xQZkj4Z/bfsrCYjaPv9JCfbtbXhJtj5Cz+oW4e8KKAFhThqxcwmuIVAzC/K4hmh8LjtfUHTehCmIC7THSYi+uHlHyjnPb4aSaNop7FtC/XS/wLwnJGZE4zo66BCFkSFi5fNF5niLpW/JlweG0CA0eZyrqbdn1uM5msn5MOi4vvbRU5mIBci2w0/tmWfaZEm6EHa0b5xJ7zggzpqMw/tuuN9iE7sjC7KsXvB267kl3B4MmfcR4O0sz6tG6OAgd971FUMfKMDbjkQlLZZl06idM8OYN/vE9cFjnwXWylvHNxYcNWyrhhPiwFP+EzQnCXRZBAqZZL8Vq3Xr46ZzcBlY65T6w7B14IJ0OYXIbbvYjkwQkcRs7hh9CZ0H6JWfagq6ZVNOrrGfJeSXjK2Zy5KmfANBN8Za9dfFHAuq/wzcgeTm+exRUfQ+/UwVqPYwCW0v3IJopptktgXunf2+n+QcHIAEtPZ1ScdZ7CJtqUcLUTVOOwZM=
  file: "EvilHack-0.5.0.x86.zip"
  skip_cleanup: true
  on:
    #tags: true
    repo: k21971/EvilHack
  prerelease: false
  name: "Release build of EvilHack 0.5.0"
  body: "This is an auto generated Release build of EvilHack 0.5.0"
