name: EvilHack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    env:
      HINTS_FILE: linux-debug.gha
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: ./sys/unix/setup.sh sys/unix/hints/$HINTS_FILE
    - name: make all
      run: make all
    - name: make install
      run: make install

  windows-build:
    runs-on: windows-latest
    env:
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: setup
      run: |
        choco install winflexbison
    - name: make install
      run: |
        ./win/win32/vs2017/ghactions.sh
    - uses: papeloto/action-zip@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: binary/
        dest: evilhack-0.6.0.zip
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          evilhack-0.6.0.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

